/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => MemosPlugin
});
module.exports = __toCommonJS(main_exports);

// src/plugin.ts
var import_obsidian10 = require("obsidian");

// src/constants.ts
var VIEW_TYPE_MEMOS = "memos-view";
var VIEW_TYPE_CAPTURE = "memos-capture-view";
var INLINE_TAG_RE = /#([\w\u4e00-\u9fff\u3040-\u309f\u30a0-\u30ff\uac00-\ud7af/-]+)/g;
var WIKILINK_RE = /\[\[([^\]|]+?)(?:\|([^\]]+?))?\]\]/g;

// src/types.ts
var DEFAULT_SETTINGS = {
  saveFolder: "Memos",
  useFixedTag: false,
  fixedTag: "",
  statsCollapsed: false,
  authorName: "",
  showAuthorInExport: false,
  showBrandingInExport: true,
  enableMood: false,
  enableSource: false,
  moodOptions: ["\u{1F4A1}", "\u{1F914}", "\u{1F60A}", "\u{1F624}", "\u{1F4D6}"],
  sourceOptions: ["thought", "kindle", "web", "conversation", "podcast"]
};

// src/view.ts
var import_obsidian5 = require("obsidian");

// src/utils.ts
function extractInlineTags(text) {
  const tags = [];
  let m;
  const re = new RegExp(INLINE_TAG_RE.source, INLINE_TAG_RE.flags);
  while ((m = re.exec(text)) !== null) {
    tags.push(m[1]);
  }
  return tags;
}
function parseTags(input) {
  return input.split(/[\s,，]+/).map((t3) => t3.replace(/^#+/, "").trim()).filter((t3) => t3.length > 0);
}

// src/memo-parser.ts
function parseMemoContent(raw, fm, frontmatterEndOffset) {
  let body = raw;
  if (frontmatterEndOffset != null) {
    body = raw.slice(frontmatterEndOffset).trimStart();
  } else if (raw.startsWith("---")) {
    const end = raw.indexOf("---", 3);
    if (end !== -1) {
      body = raw.slice(end + 3).trimStart();
    }
  }
  const inlineTags = extractInlineTags(body);
  const fmTags = [];
  if (Array.isArray(fm["tags"])) {
    for (const t3 of fm["tags"]) {
      if (typeof t3 === "string")
        fmTags.push(t3);
    }
  }
  const tags = Array.from(/* @__PURE__ */ new Set([...fmTags, ...inlineTags]));
  return { body, tags };
}

// src/stats.ts
var import_obsidian2 = require("obsidian");

// src/i18n.ts
var import_obsidian = require("obsidian");
var en = {
  openMemosView: "Open Memos view",
  quickCapture: "Quick capture",
  memoContentEmpty: "Memo content is empty.",
  memoSaved: "Memo saved!",
  saveAsMemo: "Save as Memo",
  selectionSavedAsMemo: "Selection saved as Memo!",
  memosTitle: "Memos",
  memoCount: (n) => `${n} memo${n !== 1 ? "s" : ""}`,
  newMemo: "New memo",
  randomReview: "Random review",
  sendToCanvas: "Send to Canvas",
  noMemosYet: "No memos yet. Start capturing your thoughts!",
  exportAsImage: "Export as image",
  searchImages: "Search image files\u2026",
  searchNotes: "Search notes\u2026",
  quickCaptureTitle: "Quick Capture",
  back: "Back",
  whatsOnYourMind: "What's on your mind?",
  mood: "Mood",
  source: "Source",
  insertImage: "Insert image",
  addTag: "Add tag",
  fixedTagHint: "Fixed tag: #${tag}",
  saveMemo: "Save Memo",
  addTagButton: "+ Add tag",
  tagPlaceholder: "Tag name\u2026",
  memoEmpty: "Memo cannot be empty.",
  failedToSave: "Failed to save memo: ${err}",
  memosSettings: "Memos Settings",
  saveFolder: "Save folder",
  saveFolderDesc: "Folder where new memos are saved (relative to vault root).",
  useFixedTag: "Use fixed tag",
  useFixedTagDesc: "Automatically add a tag to every memo you capture.",
  fixedTagValue: "Fixed tag value",
  fixedTagValueDesc: "This tag will be added to every memo (without #).",
  extendedMetadata: "Extended metadata",
  enableMood: "Enable mood",
  enableMoodDesc: "Show mood picker when capturing memos. Adds a mood field to frontmatter for Dataview queries.",
  moodOptions: "Mood options",
  moodOptionsDesc: "Comma-separated emojis for the mood picker.",
  enableSource: "Enable source",
  enableSourceDesc: "Show source picker when capturing memos. Adds a source field to frontmatter for Dataview queries.",
  sourceOptions: "Source options",
  sourceOptionsDesc: "Comma-separated source labels (e.g. thought, kindle, web).",
  imageExport: "Image export",
  showAuthorName: "Show author name",
  showAuthorNameDesc: "Display your name at the bottom of exported memo images.",
  authorName: "Author name",
  authorNameDesc: "Your name or brand to show on exported images.",
  showBranding: "Show branding",
  showBrandingDesc: 'Display "Quick Memos for Obsidian" at the bottom of exported images.',
  importHeading: "Import",
  importFromFlomo: "Import from Flomo",
  importFromFlomoDesc: "Select the HTML file exported from Flomo. Each memo will be converted to a .md file with proper frontmatter and saved to the save folder. Duplicate imports are automatically skipped.",
  chooseHtmlFile: "Choose HTML file",
  readingFile: "Reading ${name}...",
  importSuccess: "Successfully imported ${count} memos from Flomo!",
  importNoNew: "No new memos to import (all already exist or file is empty).",
  importFailed: "Import failed: ${err}",
  months: ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"],
  weekdays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
  heatmapTooltip: (date, count) => `${date}: ${count} memo${count !== 1 ? "s" : ""}`,
  statsTitle: "Stats",
  statTotal: "Total",
  statStreak: "Streak",
  statStreakUnit: "days",
  statToday: "Today",
  statThisMonth: "Month",
  saveAsPng: "Save as PNG",
  copyToClipboard: "Copy to clipboard",
  imageSaved: "Image saved!",
  imageSavedTo: "Image saved to ${path}",
  imageCopied: "Image copied to clipboard!",
  exportFailed: "Export failed: ${err}",
  copyFailed: "Copy failed: ${err}",
  noMemosToExport: "No memos to export.",
  exportedToCanvas: "Exported ${count} memos to Canvas!",
  noMemosInHtml: "No memos found in the HTML file."
};
var zh = {
  openMemosView: "\u6253\u5F00 Memos \u89C6\u56FE",
  quickCapture: "\u5FEB\u901F\u8BB0\u5F55",
  memoContentEmpty: "Memo \u5185\u5BB9\u4E0D\u80FD\u4E3A\u7A7A\u3002",
  memoSaved: "Memo \u5DF2\u4FDD\u5B58\uFF01",
  saveAsMemo: "\u4FDD\u5B58\u4E3A Memo",
  selectionSavedAsMemo: "\u5DF2\u4FDD\u5B58\u4E3A Memo\uFF01",
  memosTitle: "Memos",
  memoCount: (n) => `${n} \u6761 memo`,
  newMemo: "\u65B0\u5EFA memo",
  randomReview: "\u968F\u673A\u56DE\u987E",
  sendToCanvas: "\u53D1\u9001\u5230 Canvas",
  noMemosYet: "\u8FD8\u6CA1\u6709 memo\uFF0C\u5F00\u59CB\u8BB0\u5F55\u4F60\u7684\u60F3\u6CD5\u5427\uFF01",
  exportAsImage: "\u5BFC\u51FA\u4E3A\u56FE\u7247",
  searchImages: "\u641C\u7D22\u56FE\u7247\u6587\u4EF6\u2026",
  searchNotes: "\u641C\u7D22\u7B14\u8BB0\u2026",
  quickCaptureTitle: "\u5FEB\u901F\u8BB0\u5F55",
  back: "\u8FD4\u56DE",
  whatsOnYourMind: "\u6B64\u523B\u7684\u60F3\u6CD5\u2026",
  mood: "\u5FC3\u60C5",
  source: "\u6765\u6E90",
  insertImage: "\u63D2\u5165\u56FE\u7247",
  addTag: "\u6DFB\u52A0\u6807\u7B7E",
  fixedTagHint: "\u56FA\u5B9A\u6807\u7B7E\uFF1A#${tag}",
  saveMemo: "\u4FDD\u5B58 Memo",
  addTagButton: "+ \u6DFB\u52A0\u6807\u7B7E",
  tagPlaceholder: "\u6807\u7B7E\u540D\u2026",
  memoEmpty: "Memo \u4E0D\u80FD\u4E3A\u7A7A\u3002",
  failedToSave: "\u4FDD\u5B58\u5931\u8D25\uFF1A${err}",
  memosSettings: "Memos \u8BBE\u7F6E",
  saveFolder: "\u4FDD\u5B58\u6587\u4EF6\u5939",
  saveFolderDesc: "\u65B0 memo \u7684\u4FDD\u5B58\u4F4D\u7F6E\uFF08\u76F8\u5BF9\u4E8E vault \u6839\u76EE\u5F55\uFF09\u3002",
  useFixedTag: "\u4F7F\u7528\u56FA\u5B9A\u6807\u7B7E",
  useFixedTagDesc: "\u81EA\u52A8\u4E3A\u6BCF\u6761 memo \u6DFB\u52A0\u4E00\u4E2A\u6807\u7B7E\u3002",
  fixedTagValue: "\u56FA\u5B9A\u6807\u7B7E\u503C",
  fixedTagValueDesc: "\u81EA\u52A8\u6DFB\u52A0\u7684\u6807\u7B7E\uFF08\u4E0D\u542B #\uFF09\u3002",
  extendedMetadata: "\u6269\u5C55\u5143\u6570\u636E",
  enableMood: "\u542F\u7528\u5FC3\u60C5",
  enableMoodDesc: "\u8BB0\u5F55\u65F6\u663E\u793A\u5FC3\u60C5\u9009\u62E9\u5668\uFF0C\u5728 frontmatter \u4E2D\u6DFB\u52A0 mood \u5B57\u6BB5\uFF0C\u652F\u6301 Dataview \u67E5\u8BE2\u3002",
  moodOptions: "\u5FC3\u60C5\u9009\u9879",
  moodOptionsDesc: "\u9017\u53F7\u5206\u9694\u7684 emoji \u5217\u8868\u3002",
  enableSource: "\u542F\u7528\u6765\u6E90",
  enableSourceDesc: "\u8BB0\u5F55\u65F6\u663E\u793A\u6765\u6E90\u9009\u62E9\u5668\uFF0C\u5728 frontmatter \u4E2D\u6DFB\u52A0 source \u5B57\u6BB5\uFF0C\u652F\u6301 Dataview \u67E5\u8BE2\u3002",
  sourceOptions: "\u6765\u6E90\u9009\u9879",
  sourceOptionsDesc: "\u9017\u53F7\u5206\u9694\u7684\u6765\u6E90\u6807\u7B7E\uFF08\u5982 thought\u3001kindle\u3001web\uFF09\u3002",
  imageExport: "\u56FE\u7247\u5BFC\u51FA",
  showAuthorName: "\u663E\u793A\u4F5C\u8005\u540D",
  showAuthorNameDesc: "\u5728\u5BFC\u51FA\u7684 memo \u56FE\u7247\u5E95\u90E8\u663E\u793A\u4F60\u7684\u540D\u5B57\u3002",
  authorName: "\u4F5C\u8005\u540D",
  authorNameDesc: "\u663E\u793A\u5728\u5BFC\u51FA\u56FE\u7247\u4E0A\u7684\u540D\u5B57\u6216\u54C1\u724C\u3002",
  showBranding: "\u663E\u793A\u54C1\u724C\u6807\u8BC6",
  showBrandingDesc: "\u5728\u5BFC\u51FA\u56FE\u7247\u5E95\u90E8\u663E\u793A\u300CQuick Memos for Obsidian\u300D\u3002",
  importHeading: "\u5BFC\u5165",
  importFromFlomo: "\u4ECE Flomo \u5BFC\u5165",
  importFromFlomoDesc: "\u9009\u62E9\u4ECE Flomo \u5BFC\u51FA\u7684 HTML \u6587\u4EF6\u3002\u6BCF\u6761 memo \u4F1A\u88AB\u8F6C\u6362\u4E3A\u5E26 frontmatter \u7684 .md \u6587\u4EF6\u5E76\u4FDD\u5B58\u5230\u6307\u5B9A\u6587\u4EF6\u5939\u3002\u91CD\u590D\u5BFC\u5165\u4F1A\u81EA\u52A8\u8DF3\u8FC7\u3002",
  chooseHtmlFile: "\u9009\u62E9 HTML \u6587\u4EF6",
  readingFile: "\u6B63\u5728\u8BFB\u53D6 ${name}\u2026",
  importSuccess: "\u6210\u529F\u4ECE Flomo \u5BFC\u5165 ${count} \u6761 memo\uFF01",
  importNoNew: "\u6CA1\u6709\u65B0\u7684 memo \u53EF\u5BFC\u5165\uFF08\u5168\u90E8\u5DF2\u5B58\u5728\u6216\u6587\u4EF6\u4E3A\u7A7A\uFF09\u3002",
  importFailed: "\u5BFC\u5165\u5931\u8D25\uFF1A${err}",
  months: ["1\u6708", "2\u6708", "3\u6708", "4\u6708", "5\u6708", "6\u6708", "7\u6708", "8\u6708", "9\u6708", "10\u6708", "11\u6708", "12\u6708"],
  weekdays: ["\u5468\u4E00", "\u5468\u4E8C", "\u5468\u4E09", "\u5468\u56DB", "\u5468\u4E94", "\u5468\u516D", "\u5468\u65E5"],
  heatmapTooltip: (date, count) => `${date}\uFF1A${count} \u6761 memo`,
  statsTitle: "\u7EDF\u8BA1",
  statTotal: "\u603B\u8BA1",
  statStreak: "\u8FDE\u7EED",
  statStreakUnit: "\u5929",
  statToday: "\u4ECA\u65E5",
  statThisMonth: "\u672C\u6708",
  saveAsPng: "\u4FDD\u5B58\u4E3A PNG",
  copyToClipboard: "\u590D\u5236\u5230\u526A\u8D34\u677F",
  imageSaved: "\u56FE\u7247\u5DF2\u4FDD\u5B58\uFF01",
  imageSavedTo: "\u56FE\u7247\u5DF2\u4FDD\u5B58\u5230 ${path}",
  imageCopied: "\u56FE\u7247\u5DF2\u590D\u5236\u5230\u526A\u8D34\u677F\uFF01",
  exportFailed: "\u5BFC\u51FA\u5931\u8D25\uFF1A${err}",
  copyFailed: "\u590D\u5236\u5931\u8D25\uFF1A${err}",
  noMemosToExport: "\u6CA1\u6709\u53EF\u5BFC\u51FA\u7684 memo\u3002",
  exportedToCanvas: "\u5DF2\u5BFC\u51FA ${count} \u6761 memo \u5230 Canvas\uFF01",
  noMemosInHtml: "HTML \u6587\u4EF6\u4E2D\u672A\u627E\u5230 memo\u3002"
};
function t(key, vars) {
  let val = i18n[key];
  if (typeof val !== "string")
    return key;
  if (vars) {
    for (const [k, v] of Object.entries(vars)) {
      val = val.split(`\${${k}}`).join(String(v));
    }
  }
  return val;
}
function isChinese() {
  try {
    return (0, import_obsidian.getLanguage)().startsWith("zh");
  } catch (e) {
    return false;
  }
}
var i18n = isChinese() ? zh : en;

// src/stats.ts
function computeStats(memos) {
  var _a, _b;
  const dailyCounts = /* @__PURE__ */ new Map();
  for (const memo of memos) {
    dailyCounts.set(memo.dateLabel, ((_a = dailyCounts.get(memo.dateLabel)) != null ? _a : 0) + 1);
  }
  const now = /* @__PURE__ */ new Date();
  const pad = (n) => n.toString().padStart(2, "0");
  const todayLabel = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}`;
  const monthPrefix = todayLabel.slice(0, 7);
  const total = memos.length;
  const today = (_b = dailyCounts.get(todayLabel)) != null ? _b : 0;
  let thisMonth = 0;
  for (const [label, count] of dailyCounts) {
    if (label.startsWith(monthPrefix)) {
      thisMonth += count;
    }
  }
  const streak = computeStreak(dailyCounts, todayLabel);
  return { total, streak, today, thisMonth, dailyCounts };
}
function computeStreak(dailyCounts, todayLabel) {
  const [y, m, d] = todayLabel.split("-").map(Number);
  const todayDate = new Date(y, m - 1, d);
  let startOffset = dailyCounts.has(todayLabel) ? 0 : 1;
  let streak = 0;
  for (let i = startOffset; ; i++) {
    const d2 = new Date(todayDate);
    d2.setDate(d2.getDate() - i);
    const label = `${d2.getFullYear()}-${(d2.getMonth() + 1).toString().padStart(2, "0")}-${d2.getDate().toString().padStart(2, "0")}`;
    if (dailyCounts.has(label)) {
      streak++;
    } else {
      break;
    }
  }
  return streak;
}
function getLevel(count) {
  if (count === 0)
    return 0;
  if (count === 1)
    return 1;
  if (count <= 3)
    return 2;
  if (count <= 6)
    return 3;
  return 4;
}
function renderHeatmap(container, dailyCounts, onDateClick) {
  var _a;
  const MONTHS = i18n.months;
  const WEEKDAYS = i18n.weekdays;
  const wrap = container.createDiv("memos-heatmap-wrap");
  const weekdayLabels = wrap.createDiv("memos-heatmap-weekday-labels");
  weekdayLabels.createDiv("memos-heatmap-weekday-spacer");
  for (let dow = 0; dow < 7; dow++) {
    const lbl = weekdayLabels.createDiv("memos-heatmap-weekday-label");
    if (dow === 0 || dow === 2 || dow === 4) {
      lbl.textContent = WEEKDAYS[dow];
    }
  }
  const gridArea = wrap.createDiv("memos-heatmap-grid-area");
  const today = /* @__PURE__ */ new Date();
  today.setHours(0, 0, 0, 0);
  const dayOfWeek = today.getDay();
  const mondayOffset = dayOfWeek === 0 ? 6 : dayOfWeek - 1;
  const thisMonday = new Date(today);
  thisMonday.setDate(today.getDate() - mondayOffset);
  const startDate = new Date(thisMonday);
  startDate.setDate(startDate.getDate() - 16 * 7);
  const pad = (n) => n.toString().padStart(2, "0");
  const monthRow = gridArea.createDiv("memos-heatmap-month-labels");
  let prevMonth = -1;
  for (let week = 0; week < 17; week++) {
    const d = new Date(startDate);
    d.setDate(d.getDate() + week * 7);
    const month = d.getMonth();
    const monthLabel = monthRow.createDiv("memos-heatmap-month-label");
    if (month !== prevMonth) {
      monthLabel.textContent = MONTHS[month];
      prevMonth = month;
    }
  }
  const heatmap = gridArea.createDiv("memos-heatmap");
  for (let week = 0; week < 17; week++) {
    for (let dow = 0; dow < 7; dow++) {
      const d = new Date(startDate);
      d.setDate(d.getDate() + week * 7 + dow);
      const label = `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
      const count = (_a = dailyCounts.get(label)) != null ? _a : 0;
      const level = getLevel(count);
      if (d > today) {
        heatmap.createDiv("memos-heatmap-cell memos-heatmap-empty");
        continue;
      }
      const cell = heatmap.createDiv({
        cls: `memos-heatmap-cell memos-heatmap-level-${level}`,
        attr: {
          "data-tooltip": i18n.heatmapTooltip(label, count),
          "data-date": label
        }
      });
      if (count > 0) {
        cell.addEventListener("click", () => {
          onDateClick(label);
        });
      }
    }
  }
}
function renderStatsSection(container, stats, collapsed, callbacks) {
  const section = container.createDiv("memos-stats-section");
  const header = section.createDiv("memos-stats-header");
  const chevron = header.createSpan("memos-stats-chevron");
  (0, import_obsidian2.setIcon)(chevron, collapsed ? "chevron-right" : "chevron-down");
  header.createSpan({ cls: "memos-stats-title", text: i18n.statsTitle });
  header.addEventListener("click", () => {
    callbacks.onToggle();
  });
  const content = section.createDiv({
    cls: `memos-stats-content${collapsed ? " memos-stats-collapsed" : ""}`
  });
  if (!collapsed) {
    renderHeatmap(content, stats.dailyCounts, callbacks.onDateClick);
    const numbers = content.createDiv("memos-stats-numbers");
    renderStatCard(numbers, i18n.statTotal, String(stats.total));
    renderStatCard(numbers, i18n.statStreak, String(stats.streak), i18n.statStreakUnit);
    renderStatCard(numbers, i18n.statToday, String(stats.today));
    renderStatCard(numbers, i18n.statThisMonth, String(stats.thisMonth));
  }
}
function renderStatCard(container, label, value, unit) {
  const card = container.createDiv("memos-stat-card");
  const valueEl = card.createDiv("memos-stat-value");
  valueEl.createSpan({ text: value });
  if (unit) {
    valueEl.createSpan({ cls: "memos-stat-unit", text: ` ${unit}` });
  }
  card.createDiv({ cls: "memos-stat-label", text: label });
}

// src/export-image.ts
var import_obsidian3 = require("obsidian");
var LIGHT_THEME = {
  bgGradientStart: "#ffffff",
  bgGradientEnd: "#f8f9fa",
  textColor: "#1a1a1a",
  tagColor: "#6b7280",
  metaBorderColor: "rgba(0, 0, 0, 0.06)",
  timeColor: "#9ca3af",
  authorColor: "#9ca3af",
  brandingColor: "#c9cdd4"
};
var DARK_THEME = {
  bgGradientStart: "#1e1e1e",
  bgGradientEnd: "#2a2a2a",
  textColor: "#e0e0e0",
  tagColor: "#9ca3af",
  metaBorderColor: "rgba(255, 255, 255, 0.08)",
  timeColor: "#6b7280",
  authorColor: "#6b7280",
  brandingColor: "#4a4a4a"
};
var CARD_WIDTH = 440;
var PADDING_X = 28;
var PADDING_TOP = 32;
var PADDING_BOTTOM = 24;
var BORDER_RADIUS = 16;
var CONTENT_FONT_SIZE = 16;
var CONTENT_LINE_HEIGHT = 1.8;
var META_FONT_SIZE = 12;
var BRANDING_FONT_SIZE = 10;
var BRANDING_TEXT = "Quick Memos for Obsidian";
var FONT_FAMILY = "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif";
var PIXEL_RATIO = 2;
var IMAGE_EMBED_RE = /!\[\[([^\]]+)\]\]/g;
var IMAGE_MAX_WIDTH = CARD_WIDTH - PADDING_X * 2;
var IMAGE_MAX_HEIGHT = 300;
function extractImageEmbeds(content) {
  const names = [];
  let m;
  const re = new RegExp(IMAGE_EMBED_RE.source, IMAGE_EMBED_RE.flags);
  while ((m = re.exec(content)) !== null) {
    names.push(m[1]);
  }
  return names;
}
function stripImageEmbeds(content) {
  return content.replace(IMAGE_EMBED_RE, "").trim();
}
async function loadVaultImage(app, filename) {
  const files = app.vault.getFiles();
  const imageFile = files.find(
    (f) => f.name === filename || f.path.endsWith(filename)
  );
  if (!imageFile)
    return null;
  try {
    const arrayBuf = await app.vault.readBinary(imageFile);
    const blob = new Blob([arrayBuf]);
    const url = URL.createObjectURL(blob);
    return new Promise((resolve) => {
      const img = new Image();
      img.onload = () => {
        URL.revokeObjectURL(url);
        resolve(img);
      };
      img.onerror = () => {
        URL.revokeObjectURL(url);
        resolve(null);
      };
      img.src = url;
    });
  } catch (e) {
    return null;
  }
}
function fitImage(imgW, imgH, maxW, maxH) {
  const ratio = Math.min(maxW / imgW, maxH / imgH, 1);
  return { w: Math.round(imgW * ratio), h: Math.round(imgH * ratio) };
}
function parseContentSegments(content) {
  const lines = content.split("\n");
  const result = [];
  const re = new RegExp(INLINE_TAG_RE.source, INLINE_TAG_RE.flags);
  for (const line of lines) {
    const segments = [];
    let lastIndex = 0;
    let match;
    re.lastIndex = 0;
    while ((match = re.exec(line)) !== null) {
      if (match.index > lastIndex) {
        segments.push({ text: line.slice(lastIndex, match.index), isTag: false });
      }
      segments.push({ text: `#${match[1]}`, isTag: true });
      lastIndex = re.lastIndex;
    }
    if (lastIndex < line.length) {
      segments.push({ text: line.slice(lastIndex), isTag: false });
    }
    if (segments.length === 0) {
      segments.push({ text: "", isTag: false });
    }
    result.push(segments);
  }
  return result;
}
function wrapSegmentLines(ctx, segments, maxWidth, fontSize) {
  const visualLines = [];
  for (const lineSegments of segments) {
    let currentLine = [];
    let lineX = 0;
    for (const seg of lineSegments) {
      ctx.font = seg.isTag ? `500 ${fontSize}px ${FONT_FAMILY}` : `normal ${fontSize}px ${FONT_FAMILY}`;
      const chars = Array.from(seg.text);
      let buf = "";
      for (const ch of chars) {
        const testWidth = ctx.measureText(buf + ch).width;
        if (lineX + testWidth > maxWidth && (buf.length > 0 || currentLine.length > 0)) {
          if (buf.length > 0) {
            currentLine.push({ text: buf, isTag: seg.isTag, x: lineX });
            lineX += ctx.measureText(buf).width;
          }
          visualLines.push(currentLine);
          currentLine = [];
          lineX = 0;
          buf = ch;
        } else {
          buf += ch;
        }
      }
      if (buf.length > 0) {
        currentLine.push({ text: buf, isTag: seg.isTag, x: lineX });
        lineX += ctx.measureText(buf).width;
      }
    }
    visualLines.push(currentLine);
  }
  return visualLines;
}
async function generateImage(app, memo, options) {
  const theme = options.isDarkMode ? DARK_THEME : LIGHT_THEME;
  const scale = PIXEL_RATIO;
  const maxTextWidth = CARD_WIDTH - PADDING_X * 2;
  const lineHeight = CONTENT_FONT_SIZE * CONTENT_LINE_HEIGHT;
  const imageNames = extractImageEmbeds(memo.content);
  const loadedImages = [];
  for (const name of imageNames) {
    const img = await loadVaultImage(app, name);
    if (img && img.naturalWidth > 0) {
      const { w, h } = fitImage(img.naturalWidth, img.naturalHeight, IMAGE_MAX_WIDTH, IMAGE_MAX_HEIGHT);
      loadedImages.push({ img, w, h });
    }
  }
  const measureCanvas = document.createElement("canvas");
  measureCanvas.width = CARD_WIDTH * scale;
  measureCanvas.height = 1;
  const mCtx = measureCanvas.getContext("2d");
  mCtx.scale(scale, scale);
  mCtx.font = `normal ${CONTENT_FONT_SIZE}px ${FONT_FAMILY}`;
  const textContent = stripImageEmbeds(memo.content);
  const segmentLines = parseContentSegments(textContent);
  const wrappedLines = wrapSegmentLines(mCtx, segmentLines, maxTextWidth, CONTENT_FONT_SIZE);
  const contentHeight = wrappedLines.length * lineHeight;
  const imageGap = 8;
  let totalImageHeight = 0;
  if (loadedImages.length > 0) {
    totalImageHeight = imageGap;
    for (const { h } of loadedImages) {
      totalImageHeight += h + imageGap;
    }
  }
  const metaGap = 20;
  const dividerHeight = 1;
  const metaPaddingTop = 14;
  const footerHeight = META_FONT_SIZE * 1.5;
  const brandingOnSeparateLine = options.showBranding && !!options.authorName;
  const brandingHeight = brandingOnSeparateLine ? BRANDING_FONT_SIZE + 16 : 0;
  const totalHeight = PADDING_TOP + contentHeight + totalImageHeight + metaGap + dividerHeight + metaPaddingTop + footerHeight + brandingHeight + PADDING_BOTTOM;
  const canvas = document.createElement("canvas");
  canvas.width = CARD_WIDTH * scale;
  canvas.height = totalHeight * scale;
  const ctx = canvas.getContext("2d");
  ctx.scale(scale, scale);
  const grad = ctx.createLinearGradient(0, 0, CARD_WIDTH * 0.6, totalHeight * 0.6);
  grad.addColorStop(0, theme.bgGradientStart);
  grad.addColorStop(1, theme.bgGradientEnd);
  ctx.fillStyle = grad;
  roundRect(ctx, 0, 0, CARD_WIDTH, totalHeight, BORDER_RADIUS);
  ctx.fill();
  let y = PADDING_TOP + CONTENT_FONT_SIZE;
  for (const vLine of wrappedLines) {
    for (const seg of vLine) {
      if (seg.isTag) {
        ctx.font = `500 ${CONTENT_FONT_SIZE}px ${FONT_FAMILY}`;
        ctx.fillStyle = theme.tagColor;
      } else {
        ctx.font = `normal ${CONTENT_FONT_SIZE}px ${FONT_FAMILY}`;
        ctx.fillStyle = theme.textColor;
      }
      ctx.fillText(seg.text, PADDING_X + seg.x, y);
    }
    y += lineHeight;
  }
  if (loadedImages.length > 0) {
    y += imageGap;
    for (const { img, w, h } of loadedImages) {
      const imgX = PADDING_X + (maxTextWidth - w) / 2;
      ctx.save();
      roundRect(ctx, imgX, y - CONTENT_FONT_SIZE, w, h, 6);
      ctx.clip();
      ctx.drawImage(img, imgX, y - CONTENT_FONT_SIZE, w, h);
      ctx.restore();
      y += h + imageGap;
    }
  }
  const dividerY = PADDING_TOP + contentHeight + totalImageHeight + metaGap;
  ctx.fillStyle = theme.metaBorderColor;
  ctx.fillRect(PADDING_X, dividerY, maxTextWidth, dividerHeight);
  const footerY = dividerY + dividerHeight + metaPaddingTop + META_FONT_SIZE;
  const d = new Date(memo.created);
  const yyyy = d.getFullYear();
  const mm = String(d.getMonth() + 1).padStart(2, "0");
  const dd = String(d.getDate()).padStart(2, "0");
  const hh = String(d.getHours()).padStart(2, "0");
  const min = String(d.getMinutes()).padStart(2, "0");
  const timeText = `${yyyy}-${mm}-${dd} ${hh}:${min}`;
  ctx.font = `300 ${META_FONT_SIZE}px ${FONT_FAMILY}`;
  ctx.fillStyle = theme.timeColor;
  ctx.fillText(timeText, PADDING_X, footerY);
  if (options.authorName) {
    const authorText = `\u2014 ${options.authorName}`;
    ctx.font = `italic 400 ${META_FONT_SIZE}px ${FONT_FAMILY}`;
    ctx.fillStyle = theme.authorColor;
    const authorWidth = ctx.measureText(authorText).width;
    ctx.fillText(authorText, CARD_WIDTH - PADDING_X - authorWidth, footerY);
  }
  if (options.showBranding) {
    ctx.font = `300 ${BRANDING_FONT_SIZE}px ${FONT_FAMILY}`;
    ctx.fillStyle = theme.brandingColor;
    const brandingWidth = ctx.measureText(BRANDING_TEXT).width;
    if (options.authorName) {
      const brandingY = footerY + BRANDING_FONT_SIZE + 16;
      ctx.fillText(BRANDING_TEXT, CARD_WIDTH - PADDING_X - brandingWidth, brandingY);
    } else {
      ctx.fillText(BRANDING_TEXT, CARD_WIDTH - PADDING_X - brandingWidth, footerY);
    }
  }
  return new Promise((resolve, reject) => {
    canvas.toBlob(
      (blob) => {
        if (blob)
          resolve(blob);
        else
          reject(new Error("Canvas toBlob returned null"));
      },
      "image/png"
    );
  });
}
function roundRect(ctx, x, y, w, h, r) {
  ctx.beginPath();
  ctx.moveTo(x + r, y);
  ctx.lineTo(x + w - r, y);
  ctx.quadraticCurveTo(x + w, y, x + w, y + r);
  ctx.lineTo(x + w, y + h - r);
  ctx.quadraticCurveTo(x + w, y + h, x + w - r, y + h);
  ctx.lineTo(x + r, y + h);
  ctx.quadraticCurveTo(x, y + h, x, y + h - r);
  ctx.lineTo(x, y + r);
  ctx.quadraticCurveTo(x, y, x + r, y);
  ctx.closePath();
}
function renderExportContent(content, container) {
  const lines = content.split("\n");
  const re = new RegExp(INLINE_TAG_RE.source, INLINE_TAG_RE.flags);
  for (let i = 0; i < lines.length; i++) {
    if (i > 0)
      container.appendChild(document.createElement("br"));
    const line = lines[i];
    let lastIndex = 0;
    let match;
    re.lastIndex = 0;
    while ((match = re.exec(line)) !== null) {
      if (match.index > lastIndex) {
        container.appendChild(
          document.createTextNode(line.slice(lastIndex, match.index))
        );
      }
      const tagSpan = document.createElement("span");
      tagSpan.className = "memos-export-inline-tag";
      tagSpan.textContent = `#${match[1]}`;
      container.appendChild(tagSpan);
      lastIndex = re.lastIndex;
    }
    if (lastIndex < line.length) {
      container.appendChild(
        document.createTextNode(line.slice(lastIndex))
      );
    }
  }
}
async function buildExportCard(app, memo, options) {
  const card = document.createElement("div");
  card.className = "memos-export-card";
  if (options.isDarkMode)
    card.classList.add("memos-export-dark");
  const contentDiv = document.createElement("div");
  contentDiv.className = "memos-export-content";
  renderExportContent(stripImageEmbeds(memo.content), contentDiv);
  card.appendChild(contentDiv);
  const imageNames = extractImageEmbeds(memo.content);
  for (const name of imageNames) {
    const files = app.vault.getFiles();
    const imageFile = files.find(
      (f) => f.name === name || f.path.endsWith(name)
    );
    if (!imageFile)
      continue;
    try {
      const arrayBuf = await app.vault.readBinary(imageFile);
      const blob = new Blob([arrayBuf]);
      const url = URL.createObjectURL(blob);
      const imgEl = document.createElement("img");
      imgEl.src = url;
      imgEl.style.maxWidth = `${IMAGE_MAX_WIDTH}px`;
      imgEl.style.maxHeight = `${IMAGE_MAX_HEIGHT}px`;
      imgEl.style.borderRadius = "6px";
      imgEl.style.display = "block";
      imgEl.style.margin = "8px auto";
      card.appendChild(imgEl);
    } catch (e) {
    }
  }
  const meta = document.createElement("div");
  meta.className = "memos-export-meta";
  const footer = document.createElement("div");
  footer.className = "memos-export-footer";
  const d = new Date(memo.created);
  const timeSpan = document.createElement("span");
  timeSpan.className = "memos-export-time";
  const yyyy = d.getFullYear();
  const mm = String(d.getMonth() + 1).padStart(2, "0");
  const dd = String(d.getDate()).padStart(2, "0");
  const hh = String(d.getHours()).padStart(2, "0");
  const min = String(d.getMinutes()).padStart(2, "0");
  timeSpan.textContent = `${yyyy}-${mm}-${dd} ${hh}:${min}`;
  footer.appendChild(timeSpan);
  if (options.authorName) {
    const authorSpan = document.createElement("span");
    authorSpan.className = "memos-export-author";
    authorSpan.textContent = `\u2014 ${options.authorName}`;
    footer.appendChild(authorSpan);
  }
  meta.appendChild(footer);
  if (options.showBranding) {
    if (options.authorName) {
      const branding = document.createElement("div");
      branding.className = "memos-export-branding";
      branding.textContent = BRANDING_TEXT;
      meta.appendChild(branding);
    } else {
      const branding = document.createElement("span");
      branding.className = "memos-export-branding";
      branding.textContent = BRANDING_TEXT;
      footer.appendChild(branding);
    }
  }
  card.appendChild(meta);
  return card;
}
var ExportModal = class extends import_obsidian3.Modal {
  constructor(app, plugin, memo) {
    super(app);
    this.plugin = plugin;
    this.memo = memo;
  }
  async onOpen() {
    const { contentEl } = this;
    contentEl.addClass("memos-export-modal");
    const isDarkMode = document.body.classList.contains("theme-dark");
    const authorName = this.plugin.settings.showAuthorInExport ? this.plugin.settings.authorName : void 0;
    const showBranding = this.plugin.settings.showBrandingInExport;
    const cardEl = await buildExportCard(this.app, this.memo, { authorName, isDarkMode, showBranding });
    const previewContainer = contentEl.createDiv("memos-export-preview");
    const cardWrapper = previewContainer.createDiv("memos-export-card-wrapper");
    cardWrapper.appendChild(cardEl);
    setTimeout(() => {
      const containerWidth = previewContainer.clientWidth - 40;
      const cardWidth = 440;
      if (containerWidth > 0 && containerWidth < cardWidth) {
        const scale = containerWidth / cardWidth;
        cardEl.style.transform = `scale(${scale})`;
        cardEl.style.transformOrigin = "top left";
        const cardHeight = cardEl.offsetHeight;
        cardWrapper.style.width = `${cardWidth * scale}px`;
        cardWrapper.style.height = `${cardHeight * scale}px`;
        cardWrapper.style.overflow = "hidden";
      }
    }, 50);
    const btnRow = contentEl.createDiv("memos-export-btn-row");
    const saveBtn = btnRow.createEl("button", {
      cls: "memos-export-btn mod-cta",
      text: i18n.saveAsPng
    });
    saveBtn.addEventListener("click", () => this.handleSave(isDarkMode));
    const copyBtn = btnRow.createEl("button", {
      cls: "memos-export-btn",
      text: i18n.copyToClipboard
    });
    copyBtn.addEventListener("click", () => this.handleCopy(isDarkMode));
  }
  /** Build filename from memo date. */
  buildFilename() {
    const d = new Date(this.memo.created);
    return `memo-${d.getFullYear()}${String(d.getMonth() + 1).padStart(2, "0")}${String(d.getDate()).padStart(2, "0")}-${String(d.getHours()).padStart(2, "0")}${String(d.getMinutes()).padStart(2, "0")}.png`;
  }
  /** Get export options for Canvas image generation. */
  getExportOptions(isDarkMode) {
    const authorName = this.plugin.settings.showAuthorInExport ? this.plugin.settings.authorName : void 0;
    const showBranding = this.plugin.settings.showBrandingInExport;
    return { authorName, isDarkMode, showBranding };
  }
  async handleSave(isDarkMode) {
    try {
      const blob = await generateImage(this.app, this.memo, this.getExportOptions(isDarkMode));
      const fname = this.buildFilename();
      if (import_obsidian3.Platform.isMobile) {
        await this.handleMobileSave(blob, fname);
      } else {
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = fname;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        new import_obsidian3.Notice(i18n.imageSaved);
      }
      this.close();
    } catch (err) {
      new import_obsidian3.Notice(
        t("exportFailed", { err: err instanceof Error ? err.message : String(err) })
      );
    }
  }
  /** Mobile save: try Web Share API first, fall back to saving into the vault. */
  async handleMobileSave(blob, fname) {
    const file = new File([blob], fname, { type: "image/png" });
    if (navigator.share && navigator.canShare && navigator.canShare({ files: [file] })) {
      try {
        await navigator.share({ files: [file] });
        return;
      } catch (shareErr) {
        if (shareErr instanceof Error && shareErr.name === "AbortError")
          return;
      }
    }
    const saveFolder = this.plugin.settings.saveFolder;
    const vaultPath = `${saveFolder}/${fname}`;
    const arrayBuf = await blob.arrayBuffer();
    await this.app.vault.createBinary(vaultPath, arrayBuf);
    new import_obsidian3.Notice(t("imageSavedTo", { path: vaultPath }));
  }
  async handleCopy(isDarkMode) {
    try {
      const blob = await generateImage(this.app, this.memo, this.getExportOptions(isDarkMode));
      await navigator.clipboard.write([
        new ClipboardItem({ "image/png": blob })
      ]);
      new import_obsidian3.Notice(i18n.imageCopied);
      this.close();
    } catch (err) {
      new import_obsidian3.Notice(
        t("copyFailed", { err: err instanceof Error ? err.message : String(err) })
      );
    }
  }
  onClose() {
  }
};

// src/canvas-export.ts
var import_obsidian4 = require("obsidian");
var CARD_W = 260;
var CARD_H = 160;
var GAP_Y = 20;
var GROUP_GAP_X = 80;
async function exportToCanvas(app, memos, canvasName) {
  var _a;
  if (memos.length === 0) {
    new import_obsidian4.Notice(i18n.noMemosToExport);
    return;
  }
  const groups = /* @__PURE__ */ new Map();
  for (const memo of memos) {
    const groupKey = memo.tags.length > 0 ? memo.tags[0] : "untagged";
    const list = (_a = groups.get(groupKey)) != null ? _a : [];
    list.push(memo);
    groups.set(groupKey, list);
  }
  const nodes = [];
  let groupX = 0;
  for (const [, groupMemos] of groups) {
    for (let i = 0; i < groupMemos.length; i++) {
      const memo = groupMemos[i];
      nodes.push({
        id: `${memo.file.path}-${i}`,
        type: "file",
        file: memo.file.path,
        x: groupX,
        y: i * (CARD_H + GAP_Y),
        width: CARD_W,
        height: CARD_H
      });
    }
    groupX += CARD_W + GROUP_GAP_X;
  }
  const canvasData = { nodes, edges: [] };
  const filename = canvasName || `Memo Board ${(/* @__PURE__ */ new Date()).toISOString().slice(0, 10)}.canvas`;
  const path = (0, import_obsidian4.normalizePath)(filename);
  const content = JSON.stringify(canvasData, null, 2);
  const existing = app.vault.getAbstractFileByPath(path);
  if (existing && existing instanceof import_obsidian4.TFile) {
    await app.vault.modify(existing, content);
  } else {
    await app.vault.create(path, content);
  }
  const canvasFile = app.vault.getAbstractFileByPath(path);
  if (canvasFile && canvasFile instanceof import_obsidian4.TFile) {
    const leaf = app.workspace.getLeaf("tab");
    await leaf.openFile(canvasFile);
  }
  new import_obsidian4.Notice(t("exportedToCanvas", { count: memos.length }));
}

// src/view.ts
var _MemosView = class extends import_obsidian5.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    this.activeTag = null;
    this.activeDateFilter = null;
    this.memos = [];
    this.highlightedCardEl = null;
    this.refreshTimer = null;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_MEMOS;
  }
  getDisplayText() {
    return i18n.memosTitle;
  }
  getIcon() {
    return "sticky-note";
  }
  /** Debounced refresh — coalesces rapid vault events into a single refresh. */
  debouncedRefresh() {
    if (this.refreshTimer)
      clearTimeout(this.refreshTimer);
    this.refreshTimer = setTimeout(() => {
      this.refreshTimer = null;
      this.refresh();
    }, 300);
  }
  async onOpen() {
    this.contentEl.addClass("memos-view");
    await this.refresh();
    const folderPrefix = (0, import_obsidian5.normalizePath)(this.plugin.settings.saveFolder) + "/";
    this.registerEvent(
      this.app.vault.on("create", (file) => {
        if (file instanceof import_obsidian5.TFile && file.path.startsWith(folderPrefix))
          this.debouncedRefresh();
      })
    );
    this.registerEvent(
      this.app.vault.on("delete", (file) => {
        if (file instanceof import_obsidian5.TFile && file.path.startsWith(folderPrefix)) {
          const hasOpenLeaf = this.app.workspace.getLeavesOfType("markdown").some((leaf) => {
            const viewFile = leaf.view.file;
            return (viewFile == null ? void 0 : viewFile.path) === file.path;
          });
          if (hasOpenLeaf) {
            this.plugin.activateView();
          }
          this.debouncedRefresh();
        }
      })
    );
    this.registerEvent(
      this.app.metadataCache.on("changed", (file) => {
        if (file instanceof import_obsidian5.TFile && file.path.startsWith(folderPrefix))
          this.debouncedRefresh();
      })
    );
  }
  async onClose() {
    if (this.refreshTimer) {
      clearTimeout(this.refreshTimer);
      this.refreshTimer = null;
    }
  }
  async refresh() {
    await this.loadMemos();
    this.contentEl.empty();
    this.highlightedCardEl = null;
    const toolbar = this.contentEl.createDiv("memos-toolbar");
    this.renderToolbar(toolbar);
    const isMobile = this.contentEl.closest(".is-mobile") !== null;
    if (isMobile) {
      const scrollContainer = this.contentEl.createDiv("memos-cards-container");
      const statsContainer = scrollContainer.createDiv();
      const stats = computeStats(this.memos);
      renderStatsSection(statsContainer, stats, this.plugin.settings.statsCollapsed, {
        onToggle: () => this.handleStatsToggle(),
        onDateClick: (date) => this.handleDateFilter(date)
      });
      this.renderCards(scrollContainer);
    } else {
      const statsContainer = this.contentEl.createDiv();
      const stats = computeStats(this.memos);
      renderStatsSection(statsContainer, stats, this.plugin.settings.statsCollapsed, {
        onToggle: () => this.handleStatsToggle(),
        onDateClick: (date) => this.handleDateFilter(date)
      });
      const cardsContainer = this.contentEl.createDiv("memos-cards-container");
      this.renderCards(cardsContainer);
    }
  }
  async loadMemos() {
    const folder = (0, import_obsidian5.normalizePath)(this.plugin.settings.saveFolder);
    const abstractFolder = this.app.vault.getAbstractFileByPath(folder);
    if (!abstractFolder || !(abstractFolder instanceof import_obsidian5.TFolder)) {
      this.memos = [];
      return;
    }
    const files = abstractFolder.children.filter(
      (f) => f instanceof import_obsidian5.TFile && f.name.endsWith(".md")
    );
    const results = (await Promise.all(
      files.map(async (file) => {
        const cache = this.app.metadataCache.getFileCache(file);
        const fm = cache == null ? void 0 : cache.frontmatter;
        if (!fm || fm["type"] !== "memo")
          return null;
        const raw = await this.app.vault.read(file);
        return this.parseMemo(file, raw, fm, cache);
      })
    )).filter((m) => m !== null);
    results.sort((a, b) => b.created.localeCompare(a.created));
    this.memos = results;
  }
  parseMemo(file, raw, fm, cache) {
    var _a, _b;
    const fmEndOffset = (_b = (_a = cache == null ? void 0 : cache.frontmatterPosition) == null ? void 0 : _a.end) == null ? void 0 : _b.offset;
    const { body, tags } = parseMemoContent(raw, fm, fmEndOffset);
    const created = typeof fm["created"] === "string" ? fm["created"] : file.stat.ctime ? new Date(file.stat.ctime).toISOString() : (/* @__PURE__ */ new Date()).toISOString();
    const dateLabel = created.slice(0, 10);
    const mood = typeof fm["mood"] === "string" ? fm["mood"].replace(/^"|"$/g, "") : "";
    const source = typeof fm["source"] === "string" ? fm["source"].replace(/^"|"$/g, "") : "";
    return { file, content: body, tags, created, dateLabel, mood, source };
  }
  renderToolbar(el) {
    const left = el.createDiv("memos-toolbar-left");
    const count = this.memos.filter(
      (m) => (!this.activeTag || m.tags.includes(this.activeTag)) && (!this.activeDateFilter || m.dateLabel === this.activeDateFilter)
    ).length;
    left.createSpan({
      cls: "memos-count",
      text: i18n.memoCount(count)
    });
    if (this.activeTag) {
      const pill = left.createSpan({ cls: "memos-active-filter-pill" });
      pill.setText(`#${this.activeTag}`);
      const x = pill.createSpan({ cls: "memos-filter-clear", text: " \xD7" });
      x.addEventListener("click", () => {
        this.activeTag = null;
        this.refresh();
      });
    }
    if (this.activeDateFilter) {
      const pill = left.createSpan({ cls: "memos-active-filter-pill memos-date-filter-pill" });
      pill.setText(this.activeDateFilter);
      const x = pill.createSpan({ cls: "memos-filter-clear", text: " \xD7" });
      x.addEventListener("click", () => {
        this.activeDateFilter = null;
        this.refresh();
      });
    }
    const right = el.createDiv("memos-toolbar-right");
    const captureBtn = right.createDiv({
      cls: "memos-toolbar-btn",
      attr: { "aria-label": i18n.newMemo }
    });
    (0, import_obsidian5.setIcon)(captureBtn, "pencil");
    captureBtn.addEventListener("click", () => {
      this.plugin.activateCaptureView();
    });
    const randomBtn = right.createDiv({
      cls: "memos-toolbar-btn",
      attr: { "aria-label": i18n.randomReview }
    });
    (0, import_obsidian5.setIcon)(randomBtn, "dice");
    randomBtn.addEventListener("click", () => {
      this.handleRandomReview();
    });
    const canvasBtn = right.createDiv({
      cls: "memos-toolbar-btn",
      attr: { "aria-label": i18n.sendToCanvas }
    });
    (0, import_obsidian5.setIcon)(canvasBtn, "layout-dashboard");
    canvasBtn.addEventListener("click", () => {
      const filtered = this.getFilteredMemos();
      exportToCanvas(this.app, filtered);
    });
  }
  renderCards(el) {
    var _a;
    const filtered = this.getFilteredMemos();
    if (filtered.length === 0) {
      const empty = el.createDiv("memos-empty");
      empty.createSpan({ text: i18n.noMemosYet });
      return;
    }
    const groups = /* @__PURE__ */ new Map();
    for (const memo of filtered) {
      const g = (_a = groups.get(memo.dateLabel)) != null ? _a : [];
      g.push(memo);
      groups.set(memo.dateLabel, g);
    }
    for (const [date, memos] of groups) {
      const group = el.createDiv("memos-date-group");
      group.createDiv({ cls: "memos-date-header", text: date });
      for (const memo of memos) {
        this.renderCard(memo, group);
      }
    }
  }
  renderCard(memo, el) {
    const card = el.createDiv("memos-card");
    card.dataset["path"] = memo.file.path;
    const contentDiv = card.createDiv("memos-card-content");
    this.renderContentDOM(memo.content, contentDiv);
    const footer = card.createDiv("memos-card-footer");
    if (memo.tags.length > 0) {
      const tagsEl = footer.createDiv("memos-card-tags");
      for (const tag of memo.tags) {
        const pill = tagsEl.createSpan({ cls: "memos-tag-pill", text: `#${tag}` });
        pill.addEventListener("click", (e) => {
          e.stopPropagation();
          this.handleTagClick(tag);
        });
      }
    }
    const footerRight = footer.createDiv("memos-card-footer-right");
    if (memo.mood) {
      footerRight.createSpan({ cls: "memos-card-mood", text: memo.mood });
    }
    if (memo.source) {
      footerRight.createSpan({ cls: "memos-card-source", text: memo.source });
    }
    const time = footerRight.createSpan({ cls: "memos-card-time" });
    const d = new Date(memo.created);
    time.setText(
      `${d.getHours().toString().padStart(2, "0")}:${d.getMinutes().toString().padStart(2, "0")}`
    );
    const shareBtn = footerRight.createDiv({
      cls: "memos-card-share-btn",
      attr: { "aria-label": i18n.exportAsImage }
    });
    (0, import_obsidian5.setIcon)(shareBtn, "share");
    shareBtn.addEventListener("click", (e) => {
      e.stopPropagation();
      new ExportModal(this.app, this.plugin, memo).open();
    });
    card.addEventListener("click", () => {
      this.openMemo(memo.file);
    });
  }
  /** Build card content using safe DOM operations instead of innerHTML. */
  renderContentDOM(content, container) {
    const lines = content.split("\n");
    for (let i = 0; i < lines.length; i++) {
      if (i > 0)
        container.createEl("br");
      const line = lines[i];
      const embedRe = new RegExp(_MemosView.EMBED_RE.source, _MemosView.EMBED_RE.flags);
      let lastIdx = 0;
      let embedMatch;
      while ((embedMatch = embedRe.exec(line)) !== null) {
        if (embedMatch.index > lastIdx) {
          this.renderTextSegment(line.slice(lastIdx, embedMatch.index), container);
        }
        const embedName = embedMatch[1];
        this.renderEmbed(embedName, container);
        lastIdx = embedRe.lastIndex;
      }
      if (lastIdx < line.length) {
        this.renderTextSegment(line.slice(lastIdx), container);
      }
    }
  }
  /** Render a text segment with inline #tag and [[wikilink]] support. */
  renderTextSegment(text, container) {
    const tagRe = new RegExp(INLINE_TAG_RE.source, INLINE_TAG_RE.flags);
    const linkRe = new RegExp(WIKILINK_RE.source, WIKILINK_RE.flags);
    const matches = [];
    let m;
    while ((m = tagRe.exec(text)) !== null) {
      matches.push({ index: m.index, length: m[0].length, type: "tag", tagName: m[1] });
    }
    while ((m = linkRe.exec(text)) !== null) {
      matches.push({ index: m.index, length: m[0].length, type: "link", linkPath: m[1], linkAlias: m[2] });
    }
    matches.sort((a, b) => a.index - b.index);
    let lastIndex = 0;
    for (const match of matches) {
      if (match.index < lastIndex)
        continue;
      if (match.index > lastIndex) {
        container.appendText(text.slice(lastIndex, match.index));
      }
      if (match.type === "tag" && match.tagName) {
        const tagSpan = container.createSpan({ cls: "memos-inline-tag", text: `#${match.tagName}` });
        tagSpan.dataset["tag"] = match.tagName;
        tagSpan.addEventListener("click", (e) => {
          e.stopPropagation();
          this.handleTagClick(match.tagName);
        });
      } else if (match.type === "link" && match.linkPath) {
        const displayText = match.linkAlias || match.linkPath;
        const linkSpan = container.createSpan({ cls: "memos-wikilink", text: displayText });
        linkSpan.dataset["href"] = match.linkPath;
        linkSpan.addEventListener("click", (e) => {
          e.stopPropagation();
          this.app.workspace.openLinkText(match.linkPath, "", false);
        });
        linkSpan.addEventListener("mouseover", (e) => {
          this.app.workspace.trigger("hover-link", {
            event: e,
            source: VIEW_TYPE_MEMOS,
            hoverParent: this,
            targetEl: linkSpan,
            linktext: match.linkPath,
            sourcePath: ""
          });
        });
      }
      lastIndex = match.index + match.length;
    }
    if (lastIndex < text.length) {
      container.appendText(text.slice(lastIndex));
    }
  }
  /** Render a ![[embed]] — show image if it's an image file, otherwise plain text. */
  renderEmbed(name, container) {
    var _a, _b;
    const ext = (_b = (_a = name.split(".").pop()) == null ? void 0 : _a.toLowerCase()) != null ? _b : "";
    if (!_MemosView.IMAGE_EXTENSIONS.includes(ext)) {
      container.appendText(`![[${name}]]`);
      return;
    }
    const file = this.app.metadataCache.getFirstLinkpathDest(name, "");
    if (!file) {
      container.appendText(`![[${name}]]`);
      return;
    }
    const resourcePath = this.app.vault.getResourcePath(file);
    const img = container.createEl("img", {
      cls: "memos-card-image",
      attr: {
        src: resourcePath,
        alt: name,
        loading: "lazy"
      }
    });
    img.addEventListener("click", (e) => {
      e.stopPropagation();
    });
  }
  handleTagClick(tag) {
    if (tag === null) {
      this.activeTag = null;
    } else {
      this.activeTag = this.activeTag === tag ? null : tag;
    }
    this.refresh();
  }
  /** Return memos filtered by the currently active tag and date filters. */
  getFilteredMemos() {
    let filtered = this.memos;
    if (this.activeTag) {
      filtered = filtered.filter((m) => m.tags.includes(this.activeTag));
    }
    if (this.activeDateFilter) {
      filtered = filtered.filter((m) => m.dateLabel === this.activeDateFilter);
    }
    return filtered;
  }
  handleRandomReview() {
    if (this.highlightedCardEl) {
      this.highlightedCardEl.removeClass("memos-card-highlighted");
      this.highlightedCardEl = null;
    }
    const filtered = this.getFilteredMemos();
    if (filtered.length === 0)
      return;
    const idx = Math.floor(Math.random() * filtered.length);
    const target = filtered[idx];
    const cardEl = this.contentEl.querySelector(
      `[data-path="${CSS.escape(target.file.path)}"]`
    );
    if (cardEl) {
      cardEl.addClass("memos-card-highlighted");
      this.highlightedCardEl = cardEl;
      cardEl.scrollIntoView({ behavior: "smooth", block: "center" });
    }
  }
  handleDateFilter(date) {
    this.activeDateFilter = this.activeDateFilter === date ? null : date;
    this.refresh();
  }
  handleStatsToggle() {
    this.plugin.settings.statsCollapsed = !this.plugin.settings.statsCollapsed;
    this.plugin.saveSettings();
    this.refresh();
  }
  openMemo(file) {
    const existing = this.app.workspace.getLeavesOfType("markdown").find((leaf) => {
      const viewFile = leaf.view.file;
      return (viewFile == null ? void 0 : viewFile.path) === file.path;
    });
    if (existing) {
      this.app.workspace.revealLeaf(existing);
    } else {
      const leaf = this.app.workspace.getLeaf("tab");
      leaf.openFile(file);
    }
  }
};
var MemosView = _MemosView;
MemosView.IMAGE_EXTENSIONS = ["png", "jpg", "jpeg", "gif", "webp", "svg"];
MemosView.EMBED_RE = /!\[\[(.+?)\]\]/g;

// src/capture-view.ts
var import_obsidian7 = require("obsidian");

// src/tag-suggestions.ts
var import_obsidian6 = require("obsidian");
function normalizeTag(tag) {
  return tag.replace(/^#+/, "").trim();
}
function rankTagSuggestions(usages, limit = 6) {
  return usages.slice().sort((a, b) => {
    if (b.count !== a.count)
      return b.count - a.count;
    if (b.lastUsed !== a.lastUsed)
      return b.lastUsed - a.lastUsed;
    return a.tag.localeCompare(b.tag);
  }).slice(0, limit).map((usage) => usage.tag);
}
async function loadTagSuggestions(app, folderPath, options = {}) {
  var _a, _b;
  const folder = (0, import_obsidian6.normalizePath)(folderPath);
  const abstractFolder = app.vault.getAbstractFileByPath(folder);
  if (!abstractFolder || !(abstractFolder instanceof import_obsidian6.TFolder)) {
    return [];
  }
  const excluded = new Set(
    Array.from((_a = options.excludedTags) != null ? _a : [], (tag) => normalizeTag(tag)).filter(Boolean)
  );
  const usageMap = /* @__PURE__ */ new Map();
  const limit = (_b = options.limit) != null ? _b : 6;
  const files = abstractFolder.children.filter(
    (child) => child instanceof import_obsidian6.TFile && child.extension.toLowerCase() === "md"
  );
  await Promise.all(
    files.map(async (file) => {
      var _a2, _b2;
      const cache = app.metadataCache.getFileCache(file);
      const fm = cache == null ? void 0 : cache.frontmatter;
      if (!fm || fm["type"] !== "memo")
        return;
      const raw = await app.vault.read(file);
      const { tags } = parseMemoContent(raw, fm, (_b2 = (_a2 = cache == null ? void 0 : cache.frontmatterPosition) == null ? void 0 : _a2.end) == null ? void 0 : _b2.offset);
      const created = typeof fm["created"] === "string" ? Date.parse(fm["created"]) : Number.isFinite(file.stat.ctime) ? file.stat.ctime : Date.now();
      const uniqueTags = new Set(
        tags.map(normalizeTag).filter((tag) => tag.length > 0 && !excluded.has(tag))
      );
      for (const tag of uniqueTags) {
        const usage = usageMap.get(tag);
        if (usage) {
          usage.count += 1;
          usage.lastUsed = Math.max(usage.lastUsed, created);
        } else {
          usageMap.set(tag, { tag, count: 1, lastUsed: created });
        }
      }
    })
  );
  return rankTagSuggestions(Array.from(usageMap.values()), limit);
}

// src/capture-view.ts
var IMAGE_EXTENSIONS = ["png", "jpg", "jpeg", "gif", "webp", "svg"];
var ImageSuggestModal = class extends import_obsidian7.FuzzySuggestModal {
  constructor(app, onChoose) {
    super(app);
    this.onChoose = onChoose;
    this.setPlaceholder(i18n.searchImages);
  }
  getItems() {
    return this.app.vault.getFiles().filter(
      (f) => IMAGE_EXTENSIONS.includes(f.extension.toLowerCase())
    );
  }
  getItemText(file) {
    return file.path;
  }
  onChooseItem(file) {
    this.onChoose(file);
  }
};
var NoteSuggestModal = class extends import_obsidian7.FuzzySuggestModal {
  constructor(app, onChoose, onDismiss) {
    super(app);
    this.onChoose = onChoose;
    this.onDismiss = onDismiss;
    this.setPlaceholder(i18n.searchNotes);
  }
  getItems() {
    return this.app.vault.getMarkdownFiles();
  }
  getItemText(file) {
    return file.basename;
  }
  onChooseItem(file) {
    this.onChoose(file);
  }
  onClose() {
    setTimeout(() => {
      var _a;
      (_a = this.onDismiss) == null ? void 0 : _a.call(this);
    }, 50);
  }
};
var CaptureItemView = class extends import_obsidian7.ItemView {
  constructor(leaf, plugin) {
    super(leaf);
    /** Explicit tags added via the pill UI (without leading #). */
    this.tags = [];
    /** Selected mood (emoji string or empty). */
    this.selectedMood = "";
    /** Selected source (string or empty). */
    this.selectedSource = "";
    /** Suggested tags shown above the add button. */
    this.suggestedTags = [];
    /** Invalidates async suggestion loads when the view closes/reopens. */
    this.tagSuggestionLoadToken = 0;
    /** Prevents multiple wikilink modals from opening simultaneously. */
    this.wikilinkModalOpen = false;
    this.plugin = plugin;
  }
  getViewType() {
    return VIEW_TYPE_CAPTURE;
  }
  getDisplayText() {
    return i18n.quickCaptureTitle;
  }
  getIcon() {
    return "pencil";
  }
  async onOpen() {
    const container = this.contentEl;
    container.empty();
    container.addClass("memos-capture-card-container");
    const closeBtn = container.createEl("button", {
      cls: "memos-capture-close clickable-icon",
      attr: { "aria-label": i18n.back }
    });
    (0, import_obsidian7.setIcon)(closeBtn, "arrow-left");
    closeBtn.addEventListener("click", async () => {
      await this.plugin.activateView();
      this.leaf.detach();
    });
    const card = container.createDiv("memos-capture-card");
    const textareaWrap = card.createDiv("memos-capture-card-textarea-wrap");
    this.textarea = textareaWrap.createEl("textarea", {
      cls: "memos-capture-card-textarea",
      attr: { placeholder: i18n.whatsOnYourMind }
    });
    this.textarea.addEventListener("input", () => {
      this.handleWikilinkTrigger();
    });
    this.tags = [];
    this.suggestedTags = [];
    this.tagsContainer = card.createDiv("memos-capture-card-tags");
    this.renderTags();
    void this.refreshTagSuggestions();
    if (this.plugin.settings.enableMood) {
      const moodRow = card.createDiv("memos-capture-meta-row");
      moodRow.createSpan({ cls: "memos-capture-meta-label", text: i18n.mood });
      const moodPills = moodRow.createDiv("memos-capture-meta-pills");
      for (const emoji of this.plugin.settings.moodOptions) {
        const pill = moodPills.createSpan({ cls: "memos-capture-meta-pill", text: emoji });
        pill.addEventListener("click", () => {
          this.selectedMood = this.selectedMood === emoji ? "" : emoji;
          moodPills.querySelectorAll(".memos-capture-meta-pill").forEach((el) => {
            el.removeClass("is-active");
          });
          if (this.selectedMood)
            pill.addClass("is-active");
        });
      }
    }
    if (this.plugin.settings.enableSource) {
      const sourceRow = card.createDiv("memos-capture-meta-row");
      sourceRow.createSpan({ cls: "memos-capture-meta-label", text: i18n.source });
      const sourcePills = sourceRow.createDiv("memos-capture-meta-pills");
      for (const src of this.plugin.settings.sourceOptions) {
        const pill = sourcePills.createSpan({ cls: "memos-capture-meta-pill", text: src });
        pill.addEventListener("click", () => {
          this.selectedSource = this.selectedSource === src ? "" : src;
          sourcePills.querySelectorAll(".memos-capture-meta-pill").forEach((el) => {
            el.removeClass("is-active");
          });
          if (this.selectedSource)
            pill.addClass("is-active");
        });
      }
    }
    card.createDiv("memos-capture-card-divider");
    const footer = card.createDiv("memos-capture-card-footer");
    const footerLeft = footer.createDiv("memos-capture-card-footer-left");
    const footerRight = footer.createDiv("memos-capture-card-footer-right");
    const imageBtn = footerLeft.createEl("button", {
      cls: "memos-capture-card-foot-btn clickable-icon",
      attr: { "aria-label": i18n.insertImage }
    });
    (0, import_obsidian7.setIcon)(imageBtn, "image");
    imageBtn.addEventListener("click", () => {
      new ImageSuggestModal(this.app, (file) => {
        this.insertAtCursor(`![[${file.name}]]`);
      }).open();
    });
    const tagBtn = footerLeft.createEl("button", {
      cls: "memos-capture-card-foot-btn clickable-icon",
      attr: { "aria-label": i18n.addTag }
    });
    (0, import_obsidian7.setIcon)(tagBtn, "hash");
    tagBtn.addEventListener("click", () => {
      this.showTagInput();
    });
    if (this.plugin.settings.useFixedTag && this.plugin.settings.fixedTag) {
      footerLeft.createSpan({
        cls: "memos-capture-card-hint",
        text: t("fixedTagHint", { tag: this.plugin.settings.fixedTag.replace(/^#+/, "") })
      });
    }
    const saveBtn = footerRight.createEl("button", {
      cls: "memos-capture-card-save",
      text: i18n.saveMemo
    });
    saveBtn.addEventListener("click", () => {
      this.handleSave();
    });
    container.addEventListener("keydown", (e) => {
      if ((e.ctrlKey || e.metaKey) && e.key === "Enter") {
        e.preventDefault();
        this.handleSave();
      }
    });
    setTimeout(() => this.textarea.focus(), 100);
  }
  async onClose() {
    this.tagSuggestionLoadToken += 1;
    this.contentEl.empty();
  }
  // ── Tag pill UI ──────────────────────────────────────────
  /** Re-render the tags container: existing pills + the add button. */
  renderTags() {
    this.tagsContainer.empty();
    for (const tag of this.tags) {
      const pill = this.tagsContainer.createDiv("memos-capture-card-tag");
      pill.createSpan({ text: `#${tag}` });
      const removeBtn = pill.createSpan({
        cls: "memos-capture-card-tag-remove",
        text: "\xD7"
      });
      removeBtn.addEventListener("click", () => {
        this.tags = this.tags.filter((t3) => t3 !== tag);
        this.renderTags();
      });
    }
    const visibleSuggestions = this.suggestedTags.filter((tag) => !this.tags.includes(tag));
    for (const tag of visibleSuggestions) {
      const pill = this.tagsContainer.createDiv(
        "memos-capture-card-tag memos-capture-card-tag-suggestion"
      );
      pill.createSpan({ text: `#${tag}` });
      pill.addEventListener("click", () => {
        if (this.tags.includes(tag))
          return;
        this.tags.push(tag);
        this.renderTags();
      });
    }
    const addBtn = this.tagsContainer.createDiv("memos-capture-card-tag-add");
    addBtn.setText(i18n.addTagButton);
    addBtn.addEventListener("click", () => {
      this.showTagInput(addBtn);
    });
  }
  /** Replace the add-button with an inline input for entering a new tag. */
  showTagInput(replaceEl) {
    const target = replaceEl != null ? replaceEl : this.tagsContainer.querySelector(
      ".memos-capture-card-tag-add"
    );
    if (!target)
      return;
    const input = document.createElement("input");
    input.type = "text";
    input.className = "memos-capture-card-tag-input";
    input.placeholder = i18n.tagPlaceholder;
    target.replaceWith(input);
    input.focus();
    let composing = false;
    input.addEventListener("compositionstart", () => {
      composing = true;
    });
    input.addEventListener("compositionend", () => {
      composing = false;
    });
    const commit = () => {
      const values = parseTags(input.value);
      for (const v of values) {
        if (!this.tags.includes(v)) {
          this.tags.push(v);
        }
      }
      this.renderTags();
    };
    input.addEventListener("keydown", (e) => {
      if (composing)
        return;
      if (e.key === "Enter" || e.key === " " || e.key === ",") {
        e.preventDefault();
        commit();
      }
      if (e.key === "Escape") {
        e.preventDefault();
        this.renderTags();
      }
    });
    input.addEventListener("blur", () => {
      commit();
    });
  }
  /** Load tag suggestions from the memo folder and refresh the chip row. */
  async refreshTagSuggestions() {
    const loadToken = ++this.tagSuggestionLoadToken;
    const excludedTags = this.plugin.settings.useFixedTag && this.plugin.settings.fixedTag ? [this.plugin.settings.fixedTag] : [];
    try {
      const suggestions = await loadTagSuggestions(
        this.app,
        this.plugin.settings.saveFolder,
        {
          limit: 6,
          excludedTags
        }
      );
      if (loadToken !== this.tagSuggestionLoadToken)
        return;
      this.suggestedTags = suggestions;
      this.renderTags();
    } catch (_err) {
    }
  }
  // ── Helpers ──────────────────────────────────────────────
  /**
   * Detect "[[" typed in the textarea and open note suggest modal.
   * On selection: replaces the "[[" with "[[NoteName]]".
   * On dismiss: leaves the "[[" as-is so the user can type manually.
   */
  handleWikilinkTrigger() {
    if (this.wikilinkModalOpen)
      return;
    const ta = this.textarea;
    const cursor = ta.selectionStart;
    const textBefore = ta.value.slice(0, cursor);
    if (!textBefore.endsWith("[["))
      return;
    this.wikilinkModalOpen = true;
    const bracketStart = cursor - 2;
    let chosen = false;
    new NoteSuggestModal(
      this.app,
      (file) => {
        chosen = true;
        const linkText = `[[${file.basename}]]`;
        const before = ta.value.slice(0, bracketStart);
        const after = ta.value.slice(cursor);
        ta.value = before + linkText + after;
        const newPos = bracketStart + linkText.length;
        ta.selectionStart = newPos;
        ta.selectionEnd = newPos;
        ta.focus();
        this.wikilinkModalOpen = false;
      },
      () => {
        if (!chosen) {
          ta.focus();
          this.wikilinkModalOpen = false;
        }
      }
    ).open();
  }
  /** Insert text at the current cursor position in the textarea. */
  insertAtCursor(text) {
    const ta = this.textarea;
    const start = ta.selectionStart;
    const end = ta.selectionEnd;
    const before = ta.value.slice(0, start);
    const after = ta.value.slice(end);
    ta.value = before + text + after;
    const newPos = start + text.length;
    ta.selectionStart = newPos;
    ta.selectionEnd = newPos;
    ta.focus();
  }
  async handleSave() {
    const trimmed = this.textarea.value.trim();
    if (!trimmed) {
      new import_obsidian7.Notice(i18n.memoEmpty);
      return;
    }
    const explicitTags = [...this.tags];
    const inlineTags = extractInlineTags(trimmed);
    const allTags = Array.from(/* @__PURE__ */ new Set([...explicitTags, ...inlineTags]));
    const meta = {};
    if (this.selectedMood)
      meta.mood = this.selectedMood;
    if (this.selectedSource)
      meta.source = this.selectedSource;
    try {
      await this.plugin.saveMemo(trimmed, allTags, Object.keys(meta).length > 0 ? meta : void 0);
      new import_obsidian7.Notice(i18n.memoSaved);
      await this.plugin.activateView();
      this.leaf.detach();
    } catch (err) {
      new import_obsidian7.Notice(
        t("failedToSave", { err: err instanceof Error ? err.message : String(err) })
      );
    }
  }
};

// src/settings.ts
var import_obsidian9 = require("obsidian");

// src/flomo-import.ts
var import_obsidian8 = require("obsidian");
function htmlToMarkdown(contentEl) {
  var _a, _b, _c, _d, _e, _f, _g, _h, _i;
  const lines = [];
  for (const child of contentEl.children) {
    const tag = child.tagName.toLowerCase();
    if (tag === "p") {
      lines.push((_b = (_a = child.textContent) == null ? void 0 : _a.trim()) != null ? _b : "");
    } else if (tag === "ul") {
      for (const li of child.children) {
        if (li.tagName.toLowerCase() === "li") {
          lines.push(`- ${(_d = (_c = li.textContent) == null ? void 0 : _c.trim()) != null ? _d : ""}`);
        }
      }
    } else if (tag === "ol") {
      let idx = 1;
      for (const li of child.children) {
        if (li.tagName.toLowerCase() === "li") {
          lines.push(`${idx}. ${(_f = (_e = li.textContent) == null ? void 0 : _e.trim()) != null ? _f : ""}`);
          idx++;
        }
      }
    } else if (tag === "blockquote") {
      const text = (_h = (_g = child.textContent) == null ? void 0 : _g.trim()) != null ? _h : "";
      lines.push(...text.split("\n").map((l) => `> ${l}`));
    } else {
      const text = (_i = child.textContent) == null ? void 0 : _i.trim();
      if (text)
        lines.push(text);
    }
  }
  return lines.join("\n");
}
function parseFlomoHtml(html) {
  var _a, _b;
  const parser = new DOMParser();
  const doc = parser.parseFromString(html, "text/html");
  const memoEls = doc.querySelectorAll(".memo");
  const memos = [];
  for (const memoEl of memoEls) {
    const timeEl = memoEl.querySelector(".time");
    const contentEl = memoEl.querySelector(".content");
    if (!contentEl)
      continue;
    const time = (_b = (_a = timeEl == null ? void 0 : timeEl.textContent) == null ? void 0 : _a.trim()) != null ? _b : "";
    const content = htmlToMarkdown(contentEl);
    const tags = extractInlineTags(content);
    const images = [];
    const filesEl = memoEl.querySelector(".files");
    if (filesEl) {
      for (const img of filesEl.querySelectorAll("img")) {
        const src = img.getAttribute("src");
        if (src) {
          const filename = src.split("/").pop();
          if (filename)
            images.push(filename);
        }
      }
    }
    if (content.trim()) {
      memos.push({ time, content, tags, images });
    }
  }
  return memos;
}
function buildMemoFile(memo) {
  const d = new Date(memo.time.replace(" ", "T"));
  const iso = isNaN(d.getTime()) ? (/* @__PURE__ */ new Date()).toISOString() : d.toISOString();
  const tagYaml = memo.tags.length > 0 ? `tags:
${memo.tags.map((t3) => `  - ${t3}`).join("\n")}` : "tags: []";
  const frontmatter = `---
created: ${iso}
type: memo
${tagYaml}
status: active
source: "flomo"
---

`;
  let body = memo.content;
  if (memo.images.length > 0) {
    body += "\n\n" + memo.images.map((img) => `![[${img}]]`).join("\n");
  }
  return frontmatter + body;
}
function buildFilename(time, index) {
  const cleaned = time.replace(/[:\s]/g, "-").replace(/[^0-9-]/g, "");
  if (cleaned.length >= 10) {
    return `memo-${cleaned}.md`;
  }
  return `memo-flomo-import-${String(index).padStart(4, "0")}.md`;
}
async function importFlomoHtml(app, htmlContent, saveFolder) {
  const memos = parseFlomoHtml(htmlContent);
  if (memos.length === 0) {
    new import_obsidian8.Notice(i18n.noMemosInHtml);
    return 0;
  }
  const folder = (0, import_obsidian8.normalizePath)(saveFolder);
  if (!app.vault.getAbstractFileByPath(folder)) {
    await app.vault.createFolder(folder);
  }
  let imported = 0;
  const folderObj = app.vault.getAbstractFileByPath(folder);
  const existingFiles = new Set(
    folderObj instanceof import_obsidian8.TFolder ? folderObj.children.filter((f) => f instanceof import_obsidian8.TFile).map((f) => f.name) : []
  );
  for (let i = 0; i < memos.length; i++) {
    const memo = memos[i];
    const filename = buildFilename(memo.time, i);
    if (existingFiles.has(filename))
      continue;
    const fileContent = buildMemoFile(memo);
    const filePath = (0, import_obsidian8.normalizePath)(`${folder}/${filename}`);
    try {
      await app.vault.create(filePath, fileContent);
      imported++;
    } catch (err) {
      console.warn(`Failed to import memo ${filename}:`, err);
    }
  }
  return imported;
}

// src/settings.ts
var MemosSettingTab = class extends import_obsidian9.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian9.Setting(containerEl).setName(i18n.memosSettings).setHeading();
    new import_obsidian9.Setting(containerEl).setName(i18n.saveFolder).setDesc(i18n.saveFolderDesc).addText(
      (text) => text.setPlaceholder("Memos").setValue(this.plugin.settings.saveFolder).onChange(async (value) => {
        this.plugin.settings.saveFolder = value.trim() || "Memos";
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian9.Setting(containerEl).setName(i18n.useFixedTag).setDesc(i18n.useFixedTagDesc).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.useFixedTag).onChange(async (value) => {
        this.plugin.settings.useFixedTag = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.useFixedTag) {
      new import_obsidian9.Setting(containerEl).setName(i18n.fixedTagValue).setDesc(i18n.fixedTagValueDesc).addText(
        (text) => text.setPlaceholder("memo").setValue(this.plugin.settings.fixedTag).onChange(async (value) => {
          this.plugin.settings.fixedTag = value.trim().replace(/^#+/, "");
          await this.plugin.saveSettings();
        })
      );
    }
    new import_obsidian9.Setting(containerEl).setName(i18n.extendedMetadata).setHeading();
    new import_obsidian9.Setting(containerEl).setName(i18n.enableMood).setDesc(i18n.enableMoodDesc).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableMood).onChange(async (value) => {
        this.plugin.settings.enableMood = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.enableMood) {
      new import_obsidian9.Setting(containerEl).setName(i18n.moodOptions).setDesc(i18n.moodOptionsDesc).addText(
        (text) => text.setPlaceholder("\u{1F4A1}, \u{1F914}, \u{1F60A}, \u{1F624}, \u{1F4D6}").setValue(this.plugin.settings.moodOptions.join(", ")).onChange(async (value) => {
          this.plugin.settings.moodOptions = value.split(",").map((s) => s.trim()).filter(Boolean);
          await this.plugin.saveSettings();
        })
      );
    }
    new import_obsidian9.Setting(containerEl).setName(i18n.enableSource).setDesc(i18n.enableSourceDesc).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableSource).onChange(async (value) => {
        this.plugin.settings.enableSource = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.enableSource) {
      new import_obsidian9.Setting(containerEl).setName(i18n.sourceOptions).setDesc(i18n.sourceOptionsDesc).addText(
        (text) => text.setPlaceholder("thought, kindle, web, conversation, podcast").setValue(this.plugin.settings.sourceOptions.join(", ")).onChange(async (value) => {
          this.plugin.settings.sourceOptions = value.split(",").map((s) => s.trim()).filter(Boolean);
          await this.plugin.saveSettings();
        })
      );
    }
    new import_obsidian9.Setting(containerEl).setName(i18n.imageExport).setHeading();
    new import_obsidian9.Setting(containerEl).setName(i18n.showAuthorName).setDesc(i18n.showAuthorNameDesc).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showAuthorInExport).onChange(async (value) => {
        this.plugin.settings.showAuthorInExport = value;
        await this.plugin.saveSettings();
        this.display();
      })
    );
    if (this.plugin.settings.showAuthorInExport) {
      new import_obsidian9.Setting(containerEl).setName(i18n.authorName).setDesc(i18n.authorNameDesc).addText(
        (text) => text.setPlaceholder("Your name").setValue(this.plugin.settings.authorName).onChange(async (value) => {
          this.plugin.settings.authorName = value.trim();
          await this.plugin.saveSettings();
        })
      );
    }
    new import_obsidian9.Setting(containerEl).setName(i18n.showBranding).setDesc(i18n.showBrandingDesc).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showBrandingInExport).onChange(async (value) => {
        this.plugin.settings.showBrandingInExport = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian9.Setting(containerEl).setName(i18n.importHeading).setHeading();
    new import_obsidian9.Setting(containerEl).setName(i18n.importFromFlomo).setDesc(i18n.importFromFlomoDesc).addButton(
      (btn) => btn.setButtonText(i18n.chooseHtmlFile).setCta().onClick(() => {
        const input = document.createElement("input");
        input.type = "file";
        input.accept = ".html,.htm";
        input.addEventListener("change", async () => {
          var _a;
          const file = (_a = input.files) == null ? void 0 : _a[0];
          if (!file)
            return;
          new import_obsidian9.Notice(t("readingFile", { name: file.name }));
          try {
            const html = await file.text();
            const count = await importFlomoHtml(
              this.app,
              html,
              this.plugin.settings.saveFolder
            );
            if (count > 0) {
              new import_obsidian9.Notice(t("importSuccess", { count }));
            } else {
              new import_obsidian9.Notice(i18n.importNoNew);
            }
          } catch (err) {
            new import_obsidian9.Notice(
              t("importFailed", { err: err instanceof Error ? err.message : String(err) })
            );
          }
        });
        input.click();
      })
    );
  }
};

// src/plugin.ts
var MemosPlugin = class extends import_obsidian10.Plugin {
  async onload() {
    await this.loadSettings();
    this.registerView(VIEW_TYPE_MEMOS, (leaf) => new MemosView(leaf, this));
    this.registerView(VIEW_TYPE_CAPTURE, (leaf) => new CaptureItemView(leaf, this));
    (0, import_obsidian10.addIcon)("quick-memos", `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100" fill="none" stroke="currentColor" stroke-width="6" stroke-linecap="round" stroke-linejoin="round"><rect x="8" y="14" width="50" height="68" rx="6"/><line x1="20" y1="34" x2="44" y2="34"/><line x1="20" y1="46" x2="38" y2="46"/><line x1="20" y1="58" x2="42" y2="58"/><rect x="70" y="14" width="14" height="52" rx="3"/><path d="M70 66l7 14 7-14" fill="currentColor"/><line x1="70" y1="24" x2="84" y2="24" stroke-width="4"/></svg>`);
    this.addRibbonIcon("quick-memos", i18n.openMemosView, () => {
      this.activateView();
    });
    this.addCommand({
      id: "open-memos-capture",
      name: i18n.quickCapture,
      callback: () => {
        this.activateCaptureView();
      }
    });
    this.addCommand({
      id: "open-memos-view",
      name: i18n.openMemosView,
      callback: () => {
        this.activateView();
      }
    });
    this.addSettingTab(new MemosSettingTab(this.app, this));
    this.registerObsidianProtocolHandler("memo", async (params) => {
      const content = (params.content || params.text || "").trim();
      const tags = (params.tags || "").split(",").map((s) => s.trim()).filter(Boolean);
      const mood = (params.mood || "").trim();
      const source = (params.source || "").trim();
      if (!content) {
        new import_obsidian10.Notice(i18n.memoContentEmpty);
        return;
      }
      const meta = {};
      if (mood)
        meta.mood = mood;
      if (source)
        meta.source = source;
      await this.saveMemo(content, tags, Object.keys(meta).length > 0 ? meta : void 0);
      new import_obsidian10.Notice(i18n.memoSaved);
    });
    this.registerObsidianProtocolHandler("memo-view", () => {
      if (this.app.workspace.layoutReady) {
        this.activateView();
      } else {
        this.app.workspace.onLayoutReady(() => {
          this.activateView();
        });
      }
    });
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor) => {
        const selection = editor.getSelection();
        if (!selection)
          return;
        menu.addItem((item) => {
          item.setTitle(i18n.saveAsMemo).setIcon("sticky-note").onClick(async () => {
            const tags = extractInlineTags(selection);
            await this.saveMemo(selection, tags);
            new import_obsidian10.Notice(i18n.selectionSavedAsMemo);
          });
        });
      })
    );
    const EMBED_RESOLVE_TIMEOUT_MS = 5e3;
    this.registerMarkdownPostProcessor((el) => {
      const embeds = el.querySelectorAll('.internal-embed:not([class*="memos-transclusion"])');
      this.tagMemoEmbeds(embeds);
      const observer = new MutationObserver((mutations) => {
        var _a, _b, _c;
        for (const mutation of mutations) {
          for (const node of mutation.addedNodes) {
            if (node instanceof HTMLElement) {
              const added = ((_a = node.matches) == null ? void 0 : _a.call(node, ".internal-embed")) ? [node] : Array.from((_c = (_b = node.querySelectorAll) == null ? void 0 : _b.call(node, ".internal-embed")) != null ? _c : []);
              if (added.length > 0)
                this.tagMemoEmbeds(added);
            }
          }
        }
      });
      observer.observe(el, { childList: true, subtree: true });
      setTimeout(() => observer.disconnect(), EMBED_RESOLVE_TIMEOUT_MS);
    });
    this.app.workspace.onLayoutReady(() => {
      if (import_obsidian10.Platform.isMobile) {
        this.activateView();
      }
    });
  }
  onunload() {
  }
  async activateCaptureView() {
    const leaf = this.app.workspace.getLeaf("tab");
    await leaf.setViewState({ type: VIEW_TYPE_CAPTURE, active: true });
    this.app.workspace.revealLeaf(leaf);
  }
  async activateView() {
    const existing = this.app.workspace.getLeavesOfType(VIEW_TYPE_MEMOS);
    if (existing.length > 0) {
      this.app.workspace.revealLeaf(existing[0]);
      return;
    }
    const leaf = this.app.workspace.getLeaf("tab");
    await leaf.setViewState({ type: VIEW_TYPE_MEMOS, active: true });
    this.app.workspace.revealLeaf(leaf);
  }
  async saveMemo(content, tags, meta) {
    const now = /* @__PURE__ */ new Date();
    const iso = now.toISOString();
    const pad = (n, len = 2) => n.toString().padStart(len, "0");
    const dateStr = `${now.getFullYear()}-${pad(now.getMonth() + 1)}-${pad(now.getDate())}`;
    const timeStr = `${pad(now.getHours())}-${pad(now.getMinutes())}-${pad(now.getSeconds())}`;
    const ms = pad(now.getMilliseconds(), 3);
    const rand = Math.random().toString(36).slice(2, 6);
    const filename = `memo-${dateStr}-${timeStr}-${ms}-${rand}.md`;
    const allTags = [];
    if (this.settings.useFixedTag && this.settings.fixedTag) {
      allTags.push(this.settings.fixedTag.replace(/^#+/, ""));
    }
    for (const tag of tags) {
      const clean = tag.replace(/^#+/, "");
      if (clean && !allTags.includes(clean)) {
        allTags.push(clean);
      }
    }
    const tagYaml = allTags.length > 0 ? `tags:
${allTags.map((t3) => `  - ${t3}`).join("\n")}` : "tags: []";
    let extraYaml = "";
    if (meta == null ? void 0 : meta.mood)
      extraYaml += `mood: "${meta.mood}"
`;
    if (meta == null ? void 0 : meta.source)
      extraYaml += `source: "${meta.source}"
`;
    extraYaml += "status: active\n";
    const frontmatter = `---
created: ${iso}
type: memo
${tagYaml}
${extraYaml}---

`;
    const fileContent = frontmatter + content;
    const folder = (0, import_obsidian10.normalizePath)(this.settings.saveFolder);
    if (!this.app.vault.getAbstractFileByPath(folder)) {
      await this.app.vault.createFolder(folder);
    }
    const filePath = (0, import_obsidian10.normalizePath)(`${folder}/${filename}`);
    await this.app.vault.create(filePath, fileContent);
    for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_MEMOS)) {
      const view = leaf.view;
      if (view instanceof MemosView) {
        await view.refresh();
      }
    }
    return filename;
  }
  /** Tag embed elements whose source file has type: memo in frontmatter. */
  tagMemoEmbeds(embeds) {
    for (const embed of embeds) {
      if (embed.hasClass("memos-transclusion-card"))
        continue;
      const src = embed.getAttribute("src");
      if (!src)
        continue;
      const file = this.app.metadataCache.getFirstLinkpathDest(src, "");
      if (!file)
        continue;
      const cache = this.app.metadataCache.getFileCache(file);
      if (!(cache == null ? void 0 : cache.frontmatter) || cache.frontmatter["type"] !== "memo")
        continue;
      embed.addClass("memos-transclusion-card");
    }
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
